WARNING: No ICDs were found. Either,
- Install a conda package providing a OpenCL implementation (pocl, oclgrind, intel-compute-runtime, beignet) or 
- Make your system-wide implementation visible by installing ocl-icd-system conda package. 
2025-06-25 01:03:28.457801: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-06-25 01:03:28.814973: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-06-25 01:03:28.930977: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2025-06-25 01:03:28.931049: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2025-06-25 01:03:28.981660: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-06-25 01:03:34.184395: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2025-06-25 01:03:34.185200: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2025-06-25 01:03:34.185236: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Loading DLC 2.3.9...
DLC loaded in light mode; you cannot use any GUI (labeling, relabeling and standalone GUI)
Traceback (most recent call last):
  File "/gpfs/gibbs/project/higley/hd362/meso-aux-scripts/vis_stimuli_crop/vis_stimuli_on_crop_06242025.py", line 3, in <module>
    import deeplabcut
  File "/home/hd362/.conda/envs/DEEPLABCUT/lib/python3.9/site-packages/deeplabcut/__init__.py", line 37, in <module>
    from deeplabcut.create_project import (
  File "/home/hd362/.conda/envs/DEEPLABCUT/lib/python3.9/site-packages/deeplabcut/create_project/__init__.py", line 12, in <module>
    from deeplabcut.create_project.demo_data import load_demo_data
  File "/home/hd362/.conda/envs/DEEPLABCUT/lib/python3.9/site-packages/deeplabcut/create_project/demo_data.py", line 16, in <module>
    from deeplabcut.utils import auxiliaryfunctions
  File "/home/hd362/.conda/envs/DEEPLABCUT/lib/python3.9/site-packages/deeplabcut/utils/__init__.py", line 11, in <module>
    from deeplabcut.utils.auxfun_multianimal import *
  File "/home/hd362/.conda/envs/DEEPLABCUT/lib/python3.9/site-packages/deeplabcut/utils/auxfun_multianimal.py", line 34, in <module>
    from deeplabcut.utils import auxiliaryfunctions, conversioncode
  File "/home/hd362/.conda/envs/DEEPLABCUT/lib/python3.9/site-packages/deeplabcut/utils/auxiliaryfunctions.py", line 31, in <module>
    from deeplabcut.pose_estimation_tensorflow.lib.trackingutils import TRACK_METHODS
  File "/home/hd362/.conda/envs/DEEPLABCUT/lib/python3.9/site-packages/deeplabcut/pose_estimation_tensorflow/__init__.py", line 17, in <module>
    from deeplabcut.pose_estimation_tensorflow.datasets import *
  File "/home/hd362/.conda/envs/DEEPLABCUT/lib/python3.9/site-packages/deeplabcut/pose_estimation_tensorflow/datasets/__init__.py", line 16, in <module>
    from .pose_tensorpack import TensorpackPoseDataset
  File "/home/hd362/.conda/envs/DEEPLABCUT/lib/python3.9/site-packages/deeplabcut/pose_estimation_tensorflow/datasets/pose_tensorpack.py", line 45, in <module>
    from tensorpack.dataflow.parallel import MultiProcessRunnerZMQ, MultiProcessRunner
  File "/home/hd362/.conda/envs/DEEPLABCUT/lib/python3.9/site-packages/tensorpack/__init__.py", line 8, in <module>
    from tensorpack.dataflow import *
  File "/home/hd362/.conda/envs/DEEPLABCUT/lib/python3.9/site-packages/tensorpack/dataflow/__init__.py", line 50, in <module>
    _global_import(module_name)
  File "/home/hd362/.conda/envs/DEEPLABCUT/lib/python3.9/site-packages/tensorpack/dataflow/__init__.py", line 30, in _global_import
    p = __import__(name, globals(), locals(), level=1)
  File "/home/hd362/.conda/envs/DEEPLABCUT/lib/python3.9/site-packages/tensorpack/dataflow/parallel.py", line 15, in <module>
    import zmq
  File "/home/hd362/.conda/envs/DEEPLABCUT/lib/python3.9/site-packages/zmq/__init__.py", line 103, in <module>
    from zmq import backend
  File "/home/hd362/.conda/envs/DEEPLABCUT/lib/python3.9/site-packages/zmq/backend/__init__.py", line 31, in <module>
    raise original_error from None
  File "/home/hd362/.conda/envs/DEEPLABCUT/lib/python3.9/site-packages/zmq/backend/__init__.py", line 26, in <module>
    _ns = select_backend(first)
  File "/home/hd362/.conda/envs/DEEPLABCUT/lib/python3.9/site-packages/zmq/backend/select.py", line 31, in select_backend
    mod = import_module(name)
  File "/home/hd362/.conda/envs/DEEPLABCUT/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/hd362/.conda/envs/DEEPLABCUT/lib/python3.9/site-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (
ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /home/hd362/.conda/envs/DEEPLABCUT/lib/python3.9/site-packages/zmq/backend/cython/../../../../../libzmq.so.5)
